// Article titles and theme order follow the 14–18 learning content package.
export const teenLearningArticles = [
  { id: "PSY-1418-ART-01", title: "თანხმობა და პირადი საზღვრები", theme: 0 },
  { id: "LAW-1018-ART-01", title: "თანხმობა და ასაკი", theme: 0 },
  { id: "PSY-1418-ART-02", title: "სხეულის საზღვრები", theme: 0 },
  { id: "LAW-1418-ART-03", title: "შენი უფლებები", theme: 0 },
  { id: "PSY-1418-ART-03", title: "სტრესი, სტრესისგან გაშეშება და საფრთხის არიდება", theme: 1 },
  { id: "SW-ART-08", title: "როგორ ამოიცნო სექსუალური ძალადობა", theme: 2 },
  { id: "LAW-1018-ART-03", title: "სექსუალური ძალადობა ონლაინ და რეალურ ცხოვრებაში", theme: 3 },
  { id: "SW-ART-09-MYTHS", title: "მითი თუ რეალობა - ვინაა დამნაშავე?", theme: 3 },
  { id: "LAW-ALL-ART-04", title: "ვის შეგიძლია უთხრა ძალადობის შესახებ?", theme: 4 },
  { id: "SW-ART-10", title: "ვინ დაეხმარება და დაგვიცავს თუ ძალადობა უკვე მოხდა?", theme: 5 },
  { id: "SW-ART-09-SUPPORT", title: "რა გიშლის ხელს ითხოვო მხარდაჭერა?", theme: 5 },
  { id: "LAW-ALL-ART-06", title: "რა სერვისები არსებობს ბავშვის დასახმარებლად?", theme: 5 },
  { id: "JUD-1418-ART-02", title: "რას ნიშნავს სისხლის სამართლის პასუხისმგებლობა?", theme: 6 },
  { id: "JUD-1418-ART-03", title: "რა ხდება სასამართლოში და რა უფლებები გაქვს?", theme: 6 },
  { id: "JUD-1418-ART-04", title: "ვის შეიძლება შეხვდე სასამართლო პროცესის დროს", theme: 6 },
  { id: "JUD-1418-ART-09", title: "როგორ დაგიცავენ სექსუალური ძალადობის საქმეში?", theme: 6 },
  { id: "PSY-1418-ART-04", title: "ემოციური გამძლეობა და პროფესიული მხარდაჭერა", theme: 7 },
] as const;
